"""Add description field back to bands

Revision ID: 29876e0ce521
Revises: 1b4fbfae822b
Create Date: 2025-10-08 01:25:37.978191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29876e0ce521'
down_revision: Union[str, None] = '1b4fbfae822b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'description')
    # ### end Alembic commands ###
