"""Add description field to bands

Revision ID: 36f0b5621c0a
Revises: a08aea11a9bd
Create Date: 2025-10-07 00:49:03.633324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36f0b5621c0a'
down_revision: Union[str, None] = 'a08aea11a9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'description')
    # ### end Alembic commands ###
